const express=require('express'),http=require('http'),WebSocket=require('ws');
const app=express(),server=http.createServer(app),wss=new WebSocket.Server({server});
app.use(express.static('public')); app.get('/health',(_,r)=>r.json({ok:true,service:'Transporter7'}));
app.get('/api/address',async(req,res)=>{const q=String(req.query.q||'').trim();if(q.length<3)return res.json([]);try{const x=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&q='+encodeURIComponent(q),{headers:{'User-Agent':'Transporter7-prototype/1.0'}});res.json(x.ok?(await x.json()).map(a=>({display_name:a.display_name,lat:a.lat,lon:a.lon})):[])}catch(e){res.json([])}});
const users=new Map(),rides=new Map();let seq=1000;
const send=(w,m)=>w&&w.readyState===1&&w.send(JSON.stringify(m));
const drivers=()=>[...users.values()].filter(u=>u.role==='driver'&&u.online&&u.available&&u.ws.readyState===1);
const count=()=>{const n=drivers().length;for(const u of users.values())if(u.role==='passenger')send(u.ws,{type:'driver_count',count:n})};
const dist=(a,b)=>{if(!a||!b||a.lat==null||b.lat==null)return 999999;const p=Math.PI/180,R=6371,d1=(b.lat-a.lat)*p,d2=(b.lng-a.lng)*p,x=Math.sin(d1/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
wss.on('connection',ws=>{let uid=null;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='hello'){uid='u'+(++seq)+'_'+Math.random().toString(36).slice(2,7);users.set(uid,{id:uid,ws,role:m.role,name:String(m.name||'User'),online:true,available:m.role==='driver',lat:null,lng:null,rideId:null});send(ws,{type:'hello_ok',userId:uid});count();return}const u=users.get(uid);if(!u)return;
if(m.type==='profile'){if(m.name)u.name=String(m.name).slice(0,80);return}
if(m.type==='driver_status'&&u.role==='driver'){u.online=!!m.online;u.available=!!m.online&&!u.rideId;count();return}
if(m.type==='location'){u.lat=+m.lat;u.lng=+m.lng;if(u.rideId){const r=rides.get(u.rideId);if(r)for(const x of users.values())if(x.rideId===u.rideId)send(x.ws,{type:'location',role:u.role,lat:u.lat,lng:u.lng,rideId:u.rideId})}return}
if(m.type==='passenger_offer'&&u.role==='passenger'){const r={id:'R'+(++seq),passengerId:uid,passengerName:u.name,pickup:m.ride.pickup,destination:m.ride.destination,pax:+m.ride.pax||1,fare:+m.ride.fare||0,pickupCoords:m.ride.pickupCoords||null,status:'searching',createdAt:Date.now()};rides.set(r.id,r);u.rideId=r.id;const ds=drivers().sort((a,b)=>dist(a,r.pickupCoords)-dist(b,r.pickupCoords));if(!ds.length){u.rideId=null;r.status='no_driver';send(ws,{type:'no_driver',rideId:r.id});return}for(const d of ds)send(d.ws,{type:'ride_call',ride:r,callSeconds:20,nearbyKm:dist(d,r.pickupCoords)});send(ws,{type:'searching',rideId:r.id,driverCount:ds.length});return}
if(m.type==='driver_pass')return;
if(m.type==='driver_accept'){const r=rides.get(m.rideId),d=u;if(!r||r.status!=='searching'||d.role!=='driver'||!d.online||!d.available){send(ws,{type:'ride_lost',rideId:m.rideId});return}r.status='accepted';r.driverId=uid;r.driverName=d.name;d.available=false;d.rideId=r.id;const p=users.get(r.passengerId);send(p?.ws,{type:'matched',ride:r,driver:{id:uid,name:d.name,lat:d.lat,lng:d.lng}});send(ws,{type:'accepted',ride:r});for(const x of drivers())if(x.id!==uid)send(x.ws,{type:'ride_taken',rideId:r.id});count();return}
if(m.type==='ride_state'){const r=rides.get(m.rideId);if(!r)return;r.status=m.state;const p=users.get(r.passengerId),d=users.get(r.driverId);send(p?.ws,{type:'ride_state',state:r.status,ride:r});send(d?.ws,{type:'ride_state',state:r.status,ride:r});if(m.state==='completed'){if(p)p.rideId=null;if(d){d.rideId=null;d.available=d.online}count()}return}
if(m.type==='cancel_ride'){const r=rides.get(m.rideId);if(!r)return;r.status='cancelled';const p=users.get(r.passengerId),d=users.get(r.driverId);if(p)p.rideId=null;if(d){d.rideId=null;d.available=d.online}send(p?.ws,{type:'cancelled',ride:r});send(d?.ws,{type:'cancelled',ride:r});count()}
});ws.on('close',()=>{if(!uid)return;const u=users.get(uid);if(u?.rideId){const r=rides.get(u.rideId);if(r&&r.status==='searching'){r.status='cancelled';for(const x of drivers())send(x.ws,{type:'ride_cancelled',rideId:r.id})}}users.delete(uid);count()})});
server.listen(process.env.PORT||3000,()=>console.log('Transporter7 ready'));
